CREATE TABLE familias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    quantidade_moradores INTEGER NOT NULL,
    ativa BOOLEAN NOT NULL,
    status_fila VARCHAR(255) NOT NULL,
    prioridade INTEGER NOT NULL,
    numero_senha INTEGER,
    data_cadastro DATE NOT NULL,
    CONSTRAINT uk_familias_cpf UNIQUE (cpf)
);

CREATE TABLE entregas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    familia_id BIGINT NOT NULL,
    senha INTEGER NOT NULL,
    data_entrega TIMESTAMP NOT NULL,
    CONSTRAINT fk_entregas_familia FOREIGN KEY (familia_id) REFERENCES familias (id)
);

CREATE INDEX idx_familias_status_fila ON familias (status_fila);
CREATE INDEX idx_familias_prioridade ON familias (prioridade);
CREATE INDEX idx_entregas_familia_id ON entregas (familia_id);
CREATE INDEX idx_entregas_data_entrega ON entregas (data_entrega);
