ALTER TABLE familias ADD COLUMN numero VARCHAR(20) NOT NULL DEFAULT 'S/N';
ALTER TABLE familias ADD COLUMN bairro VARCHAR(255) NOT NULL DEFAULT '-';
ALTER TABLE familias ADD COLUMN cidade VARCHAR(255) NOT NULL DEFAULT '-';
